NB_REALIZED_TASKS_KEY = 'NbRealizedTasks'
TOTAL_WORKING_DURATION_KEY = 'TotalWorkingDuration'
TOTAL_TRAVELING_DURATION_KEY = 'TotalTravelingDuration'
TOTAL_TRAVELING_DISTANCE_KEY = 'TotalTravelingDistance'
TOTAL_IDLE_TIME_KEY = 'TotalIdleTime'
KPI_KEYS = [NB_REALIZED_TASKS_KEY, TOTAL_WORKING_DURATION_KEY, TOTAL_TRAVELING_DURATION_KEY,
            TOTAL_TRAVELING_DISTANCE_KEY, TOTAL_IDLE_TIME_KEY]