####################
# Variables to set #
####################

# For solution feasibility check
SAVE_SOLUTIONS_FEASIBILITY_CHECK_AS_FILE = False
SAVE_SOLUTIONS_ANALYSIS_AS_FILES = False
SHOW_FIGURES_IN_FEASIBILITY_CHECK = True
SAVE_FIGURES_IN_FEASIBILITY_CHECK = False
TOLERANCE_IN_MINUTES_IN_TIME_CONSTRAINTS_CHECK = 0

# For IP optimization
SOLVING_PROCESS_TIME_LIMIT_IN_SECONDS = 30 * 60
MUTE_SOLVING_PROCESS = False
