LINE_BREAK_STRING = "\r\n"

POSSIBLE_EXTENSIONS = ['.json', '.txt', '.xlsx', '.xls']

META_DATA_CORE_KEY = 'core'
META_DATA_CASE_KEY = 'case'
META_DATA_VERSION_KEY = 'version'
META_DATA_SOLVING_METHOD_KEY = 'solving_method'
META_DATA_SOLVING_PARAMETERS_KEY = 'solving parameters'

CAMEL_CASE = 'CamelCase'
SNAKE_CASE = 'snake_case'

SOLUTION_NAME_PREFIX = 'solution_'
SOLUTION_NAME_PREFIX_BIS = 'Solution'
SOLUTION_FILE_NAME_POSSIBLE_PREFIXES = [SOLUTION_NAME_PREFIX, SOLUTION_NAME_PREFIX_BIS]
SOLUTION_SOLVING_METHOD_SYMBOL = 'By'
SOLUTION_SOLVING_PARAMETERS_LEFT_SYMBOL = '('
SOLUTION_SOLVING_PARAMETERS_RIGHT_SYMBOL = ')'
SOLUTION_SOLVING_PARAMETERS_SEPARATOR_SYMBOL = ','
SOLUTION_FILE_EXTENSION = '.txt'
SOLUTIONS_WITH_VERSION_DIRECTORY_RELATIVE_PATH = 'solutions'

SOLUTION_ANALYSIS_FILE_NAME_SUFFIX = 'Analysis'

INSTANCE_NAME_PREFIX = 'instance_'
INSTANCE_NAME_PREFIX_BIS = 'Instance'
INSTANCE_FILE_NAME_POSSIBLE_PREFIXES = [INSTANCE_NAME_PREFIX, INSTANCE_NAME_PREFIX_BIS]
INSTANCE_VERSION_SYMBOL = 'V'
INSTANCE_FILE_EXTENSION = '.xlsx'
INSTANCE_FILE_POSSIBLE_EXTENSIONS = ['.xlsx', '.json']
INSTANCES_WITH_VERSION_DIRECTORY_RELATIVE_PATH = 'instances'
INSTANCE_SET_NAME_PREFIX = 'instances'

TEACHING_DATA_DIRECTORY_RELATIVE_PATH = 'data/teaching'

INPUTS_DIRECTORY_RELATIVE_PATH = 'inputs'
OUTPUTS_DIRECTORY_RELATIVE_PATH = 'outputs'

CHECKING_ROUTINE_KEY = 'checking'
OPTIMIZING_ROUTINE_KEY = 'optimizing'
EXPLAINING_ROUTINE_KEY = 'explaining'
