########################
# About main processes #
########################

# Explanation process
RUN_EXPLANATION_PROCESS = 'explaining'
RUN_EXPLAINER_ON_DEMO_SOLUTION_AS_EXPLANATION_PROCESS = 'explaining_demo'
RUN_EXPLAINER_ON_GIVEN_SOLUTION_AS_EXPLANATION_PROCESS = 'explaining_solution'
RUN_EXPLANATION_COMPUTATION_ANALYSIS_AS_EXPLANATION_PROCESS = 'explanation_computation_analysis'
RUN_COUNTERFACTUAL_EXPLANATION_COMPUTATION_ANALYSIS_AS_EXPLANATION_PROCESS = (
    'counterfactual_explanation_computation_analysis'
)

# Evaluation process
RUN_EVALUATION_PROCESS = 'evaluating'

# Optimization and reoptimizing processes
RUN_OPTIMIZATION_PROCESS = 'optimizing'
RUN_REOPTIMIZATION_PROCESS = 'reoptimizing'
RUN_GREEDY_ALGORITHM_AS_OPTIMIZATION_PROCESS = 'greedy_algorithm'
RUN_STOCHASTIC_HEURISTIC_AS_OPTIMIZATION_PROCESS = 'stochastic_heuristic'
RUN_NEIGHBORHOOD_SEARCH_AS_OPTIMIZATION_PROCESS = 'neighborhood_search'

# Analysis process
RUN_ANALYSIS_PROCESS = 'analyzing'

# Teaching process
RUN_TEACHING_PROCESS = 'teaching'
RUN_SOLUTION_FEASIBILITY_CHECK_AS_TEACHING_PROCESS = 'teaching_checking'
RUN_INSTANCE_IP_SOLVING_AS_TEACHING_PROCESS = 'teaching_optimizing'


#########
# Other #
#########

LINE_BREAK_STRING = "\r\n"

POSSIBLE_EXTENSIONS = ['.json', '.txt', '.xlsx', '.xls', '.DS_Store', '.gitkeep']

META_DATA_CORE_KEY = 'core'
META_DATA_CASE_KEY = 'case'
META_DATA_VERSION_KEY = 'version'
META_DATA_SOLVING_METHOD_KEY = 'solving_method'
META_DATA_SOLVING_PARAMETERS_KEY = 'solving parameters'

CAMEL_CASE = 'CamelCase'
SNAKE_CASE = 'snake_case'

# Data directories
DEFAULT_INPUTS_DIRECTORY_RELATIVE_PATH = 'inputs'
DEFAULT_OUTPUTS_DIRECTORY_RELATIVE_PATH = 'outputs'
TEACHING_DATA_DIRECTORY_RELATIVE_PATH = 'data/teaching'

# About instance files and names
INSTANCE_NAME_PREFIX = 'instance_'
INSTANCE_NAME_PREFIX_BIS = 'Instance'
INSTANCE_FILE_NAME_POSSIBLE_PREFIXES = [INSTANCE_NAME_PREFIX, INSTANCE_NAME_PREFIX_BIS]
INSTANCE_VERSION_SYMBOL = 'V'
INSTANCE_FILE_EXTENSION = '.xlsx'
INSTANCE_FILE_POSSIBLE_EXTENSIONS = ['.xlsx', '.json']
INSTANCES_WITH_VERSION_DIRECTORY_RELATIVE_PATH = 'instances'
INSTANCE_SET_NAME_PREFIX = 'instances'

# About solution files and names
SOLUTION_NAME_PREFIX = 'solution_'
SOLUTION_NAME_PREFIX_BIS = 'Solution'
SOLUTION_FILE_NAME_POSSIBLE_PREFIXES = [SOLUTION_NAME_PREFIX, SOLUTION_NAME_PREFIX_BIS]
SOLUTION_SOLVING_METHOD_SYMBOL = 'by'
SOLUTION_SOLVING_METHOD_SYMBOL_BIS = 'By'
SOLUTION_SOLVING_PARAMETERS_LEFT_SYMBOL = '('
SOLUTION_SOLVING_PARAMETERS_RIGHT_SYMBOL = ')'
SOLUTION_SOLVING_PARAMETERS_SEPARATOR_SYMBOL = ','
SOLUTION_FILE_EXTENSION = '.txt'
SOLUTIONS_WITH_VERSION_DIRECTORY_RELATIVE_PATH = 'solutions'
SOLUTION_ANALYSIS_FILE_NAME_SUFFIX = 'analysis'
SOLUTION_ANALYSIS_FILE_NAME_SUFFIX_BIS = 'Analysis'

# About solving method
GREEDY_SOLVING_METHOD = 'greedy'
STOCHASTIC_HEURISTIC_SOLVING_METHOD = 'stochastic_heuristic'
NEIGHBORHOOD_SEARCH_SOLVING_METHOD = 'neighborhood_search'
HEURISTICS_SOLVING_METHODS = [
    GREEDY_SOLVING_METHOD, STOCHASTIC_HEURISTIC_SOLVING_METHOD, NEIGHBORHOOD_SEARCH_SOLVING_METHOD
]
