LINE_BREAK_STRING = "\r\n"

CORE_KEY = "core"

SOLUTION_FILE_NAME_PREFIX = "solution_"  # "Solution"
SOLUTION_METHOD_STRING = "By"
SOLUTION_ANALYSIS_FILE_NAME_SUFFIX = "Analysis"
SOLUTION_FILE_EXTENSION = ".txt"
SOLUTIONS_WITH_VERSION_DIRECTORY_RELATIVE_PATH = "solutions"

INSTANCE_FILE_NAME_PREFIX = "instance_"  # "Instance"
INSTANCE_VERSION_STRING = "V"
INSTANCE_FILE_EXTENSION = ".xlsx"
INSTANCES_WITH_VERSION_DIRECTORY_RELATIVE_PATH = "instances"
INSTANCE_SET_NAME_PREFIX = "instances"

TEACHING_DATA_DIRECTORY_RELATIVE_PATH = "data/teaching"

INPUTS_DIRECTORY_RELATIVE_PATH = "inputs"
OUTPUTS_DIRECTORY_RELATIVE_PATH = "outputs"
