NB_PERFORMED_TASKS_KEY = 'nb performed tasks'
TOTAL_WORKING_DURATION_KEY = 'total working duration'
TOTAL_TRAVELING_DURATION_KEY = 'total traveling duration'
TOTAL_TRAVELING_DISTANCE_KEY = 'total traveling distance'
TOTAL_IDLE_TIME_KEY = 'total idle time'
KPI_KEYS = [NB_PERFORMED_TASKS_KEY, TOTAL_WORKING_DURATION_KEY, TOTAL_TRAVELING_DURATION_KEY,
            TOTAL_TRAVELING_DISTANCE_KEY, TOTAL_IDLE_TIME_KEY]