# Local libraries
from src.utils.language import *


####################
# Variables to set #
####################

# For explaining demo solution
# EXPLAINER_DEMO_SOLUTION_LANGUAGE = LANGUAGE_ENGLISH_KEY
EXPLAINER_DEMO_SOLUTION_LANGUAGE = LANGUAGE_FRENCH_KEY
EXPLAINER_DEMO_SOLUTION_ENABLE_HISTORY = True
EXPLAINER_DEMO_SOLUTION_ENABLE_SCENARIO = True
EXPLAINER_DEMO_SOLUTION_ENABLE_COUNTERFACTUAL = True
EXPLAINER_DEMO_SOLUTION_ENABLE_USING_ALREADY_COMPUTED_CONTRASTIVE_EXPLANATIONS = False

# For explaining the solution in default inputs
EXPLAINER_DEFAULT_SOLUTION_LANGUAGE = LANGUAGE_ENGLISH_KEY
# EXPLAINER_DEFAULT_SOLUTION_LANGUAGE = LANGUAGE_FRENCH_KEY
EXPLAINER_DEFAULT_SOLUTION_ENABLE_HISTORY = True
EXPLAINER_DEFAULT_SOLUTION_ENABLE_SCENARIO = True
EXPLAINER_DEFAULT_SOLUTION_ENABLE_COUNTERFACTUAL = True


