ROUTES_FIGURE_KEY = 'routes'
ROUTES_FIGURE_KEY_BIS = 'Routes'
SCHEDULES_FIGURE_KEY = 'schedules'
SCHEDULES_FIGURE_KEY_BIS = 'Schedules'
KPIS_FIGURE_KEY = 'KPIs'
KPIS_FIGURE_KEY_BIS = 'KPIs'
FIGURES_KEYS = [ROUTES_FIGURE_KEY, SCHEDULES_FIGURE_KEY, KPIS_FIGURE_KEY]
FIGURE_DPI_FOR_SAVING = 300
